export const GET_GOOGLE_INFOS="http://localhost:8000/get_google_infos"
export const GET_SENTIMENT_BY_URL="http://localhost:8000/get_sentiment_by_url"
export const GET_SENTIMENT_BY_URLS="http://localhost:8000/get_sentiments_by_urls"
export const GET_SENTIMENT_BY_QUERY="http://localhost:8000/get_sentiments_by_query"
export const GET_PERSONAL_DATA="http://localhost:8000/get_personal_data"
export const GET_HOLEHE_INFOS="http://localhost:8000/get_holehe_infos"